{
 "title": "Сравнение прогноза и фактической влажности по городам",
 "description": "Влажность по городам",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Сравнение влажности (%) прогноза (последнего) и фактической  по источнику OpenWeatherMap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tfcst.forecast_dttm,\r\n\tdm.city as city,\r\n\tfcst.humidity as `Влажность пронгоз`,\r\n\tdm.humidity as `Влажность факт`\r\n  from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nJOIN main.dm_forecast_actual_data_distributed fcst ON toStartOfFiveMinutes(dm.create_dttm) = toStartOfFiveMinutes(forecast_dttm)\r\n\tAND dm.owd_id = fcst.owd_id\r\n\tAND dm.lang = fcst.lang\r\n\tAND dm.city = fcst.city\r\nwhere owd_name = 'OpenWeatherMap'\r\nand dm.lang = 'ru'\r\norder by dm.city\r\nSETTINGS distributed_product_mode = 'allow'"
    }
   ]
  },
  {
   "title": "Сравнение влажности (%) прогноза (последнего) и фактической  по источнику WeatherApi",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tfcst.forecast_dttm,\r\n\tdm.city as city,\r\n\tfcst.humidity as `Влажность пронгоз`,\r\n\tdm.humidity as `Влажность факт`\r\n  from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nJOIN main.dm_forecast_actual_data_distributed fcst ON toStartOfFiveMinutes(dm.create_dttm) = toStartOfFiveMinutes(forecast_dttm)\r\n\tAND dm.owd_id = fcst.owd_id\r\n\tAND dm.lang = fcst.lang\r\n\tAND dm.city = fcst.city\r\nwhere owd_name = 'WeatherApi'\r\nand dm.lang = 'ru'\r\norder by dm.city\r\nSETTINGS distributed_product_mode = 'allow'"
    }
   ]
  },
  {
   "title": "Точность прогноза влажности (%) по источнику OpenWeatherMap (по последнему прогнозу)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tfcst.forecast_dttm,\r\n\tdm.city as city,\r\n\tfloor(IF(dm.humidity > fcst.humidity, 100 - (dm.humidity - fcst.humidity), 100 - (fcst.humidity - dm.humidity)), 2) AS `Точность` from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nJOIN main.dm_forecast_actual_data_distributed fcst ON toStartOfFiveMinutes(dm.create_dttm) = toStartOfFiveMinutes(forecast_dttm)\r\n\tAND dm.owd_id = fcst.owd_id\r\n\tAND dm.lang = fcst.lang\r\n\tAND dm.city = fcst.city\r\nwhere owd_name = 'OpenWeatherMap'\r\nand dm.lang = 'ru'\r\norder by dm.city\r\nSETTINGS distributed_product_mode = 'allow'"
    }
   ]
  },
  {
   "title": "Точность прогноза влажности (%) по источнику WeatherApi (по последнему прогнозу)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tfcst.forecast_dttm,\r\n\tdm.city as city,\r\n\tfloor(IF(dm.humidity > fcst.humidity, 100 - (dm.humidity - fcst.humidity), 100 - (fcst.humidity - dm.humidity)), 2) AS `Точность` from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nJOIN main.dm_forecast_actual_data_distributed fcst ON toStartOfFiveMinutes(dm.create_dttm) = toStartOfFiveMinutes(forecast_dttm)\r\n\tAND dm.owd_id = fcst.owd_id\r\n\tAND dm.lang = fcst.lang\r\n\tAND dm.city = fcst.city\r\nwhere owd_name = 'WeatherApi'\r\nand dm.lang = 'ru'\r\norder by dm.city\r\nSETTINGS distributed_product_mode = 'allow'"
    }
   ]
  },
  {
   "title": "Средняя точность прогноза влажности (%) по источнику OpenWeatherMap (по последнему прогнозу)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tdm.city as city,\r\n\tfloor(avg(IF(dm.humidity > fcst.humidity, 100 - (dm.humidity - fcst.humidity), 100 - (fcst.humidity - dm.humidity))), 2) AS `Точность прогноза` from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nJOIN main.dm_forecast_actual_data_distributed fcst ON toStartOfFiveMinutes(dm.create_dttm) = toStartOfFiveMinutes(forecast_dttm)\r\n\tAND dm.owd_id = fcst.owd_id\r\n\tAND dm.lang = fcst.lang\r\n\tAND dm.city = fcst.city\r\nwhere owd_name = 'OpenWeatherMap'\r\nand forecast_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\nand dm.lang = 'ru'\r\nGROUP BY dm.city\r\norder by `Точность прогноза`\r\nSETTINGS distributed_product_mode = 'allow'"
    }
   ]
  },
  {
   "title": "Средняя точность прогноза влажности (%) по источнику WeatherApi (по последнему прогнозу)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tdm.city as city,\r\n\tfloor(avg(IF(dm.humidity > fcst.humidity, 100 - (dm.humidity - fcst.humidity), 100 - (fcst.humidity - dm.humidity))), 2) AS `Точность прогноза` from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nJOIN main.dm_forecast_actual_data_distributed fcst ON toStartOfFiveMinutes(dm.create_dttm) = toStartOfFiveMinutes(forecast_dttm)\r\n\tAND dm.owd_id = fcst.owd_id\r\n\tAND dm.lang = fcst.lang\r\n\tAND dm.city = fcst.city\r\nwhere owd_name = 'WeatherApi'\r\nand forecast_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\nand dm.lang = 'ru'\r\nGROUP BY dm.city\r\norder by `Точность прогноза`\r\nSETTINGS distributed_product_mode = 'allow'"
    }
   ]
  },
  {
   "title": "Сравнение влажности (%) прогноза (по следующему дню) и фактической  по источнику OpenWeatherMap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tfcst.forecast_dttm,\r\n\tdm.city as city,\r\n\tfcst.humidity as `Влажность пронгоз`,\r\n\tdm.humidity as `Влажность факт`\r\n  from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nJOIN main.dm_forecast_all_data_distributed fcst ON toStartOfFiveMinutes(dm.create_dttm) = toStartOfFiveMinutes(forecast_dttm)\r\n\tAND dm.owd_id = fcst.owd_id\r\n\tAND dm.lang = fcst.lang\r\n\tAND dm.city = fcst.city\r\nwhere owd_name = 'OpenWeatherMap'\r\nand dm.lang = 'ru'\r\nand fcst.forecast_diff = 24\r\norder by dm.city\r\nSETTINGS distributed_product_mode = 'allow'"
    }
   ]
  },
  {
   "title": "Сравнение влажности (%) прогноза (по следующему дню) и фактической  по источнику WeatherApi",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tfcst.forecast_dttm,\r\n\tdm.city as city,\r\n\tfcst.humidity as `Влажность пронгоз`,\r\n\tdm.humidity as `Влажность факт`\r\n  from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nJOIN main.dm_forecast_all_data_distributed fcst ON toStartOfFiveMinutes(dm.create_dttm) = toStartOfFiveMinutes(forecast_dttm)\r\n\tAND dm.owd_id = fcst.owd_id\r\n\tAND dm.lang = fcst.lang\r\n\tAND dm.city = fcst.city\r\nwhere owd_name = 'WeatherApi'\r\nand dm.lang = 'ru'\r\nand fcst.forecast_diff = 24\r\norder by dm.city\r\nSETTINGS distributed_product_mode = 'allow'"
    }
   ]
  },
  {
   "title": "Точность прогноза влажности (%) по источнику OpenWeatherMap (по следующему дню)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tfcst.forecast_dttm,\r\n\tdm.city as city,\r\n\tfloor(IF(dm.humidity > fcst.humidity, 100 - (dm.humidity - fcst.humidity), 100 - (fcst.humidity - dm.humidity)), 2) AS `Точность` from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nJOIN main.dm_forecast_all_data_distributed fcst ON toStartOfFiveMinutes(dm.create_dttm) = toStartOfFiveMinutes(forecast_dttm)\r\n\tAND dm.owd_id = fcst.owd_id\r\n\tAND dm.lang = fcst.lang\r\n\tAND dm.city = fcst.city\r\nwhere owd_name = 'OpenWeatherMap'\r\nand dm.lang = 'ru'\r\nand fcst.forecast_diff = 24\r\norder by dm.city\r\nSETTINGS distributed_product_mode = 'allow'"
    }
   ]
  },
  {
   "title": "Точность прогноза влажности (%) по источнику WeatherApi (по следующему дню)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tfcst.forecast_dttm,\r\n\tdm.city as city,\r\n\tfloor(IF(dm.humidity > fcst.humidity, 100 - (dm.humidity - fcst.humidity), 100 - (fcst.humidity - dm.humidity)), 2) AS `Точность` from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nJOIN main.dm_forecast_all_data_distributed fcst ON toStartOfFiveMinutes(dm.create_dttm) = toStartOfFiveMinutes(forecast_dttm)\r\n\tAND dm.owd_id = fcst.owd_id\r\n\tAND dm.lang = fcst.lang\r\n\tAND dm.city = fcst.city\r\nwhere owd_name = 'WeatherApi'\r\nand dm.lang = 'ru'\r\nand fcst.forecast_diff = 24\r\norder by dm.city\r\nSETTINGS distributed_product_mode = 'allow'"
    }
   ]
  },
  {
   "title": "Средняя точность прогноза влажности (%) по источнику OpenWeatherMap (по следующему дню)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tdm.city as city,\r\n\tfloor(avg(IF(dm.humidity > fcst.humidity, 100 - (dm.humidity - fcst.humidity), 100 - (fcst.humidity - dm.humidity))), 2) AS `Точность прогноза` from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nJOIN main.dm_forecast_all_data_distributed fcst ON toStartOfFiveMinutes(dm.create_dttm) = toStartOfFiveMinutes(forecast_dttm)\r\n\tAND dm.owd_id = fcst.owd_id\r\n\tAND dm.lang = fcst.lang\r\n\tAND dm.city = fcst.city\r\nwhere owd_name = 'OpenWeatherMap'\r\nand forecast_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\nand dm.lang = 'ru'\r\nand fcst.forecast_diff = 24\r\nGROUP BY dm.city\r\norder by `Точность прогноза`\r\nSETTINGS distributed_product_mode = 'allow'"
    }
   ]
  },
  {
   "title": "Средняя точность прогноза влажности (%) по источнику WeatherApi (по следующему дню)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tdm.city as city,\r\n\tfloor(avg(IF(dm.humidity > fcst.humidity, 100 - (dm.humidity - fcst.humidity), 100 - (fcst.humidity - dm.humidity))), 2) AS `Точность прогноза` from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nJOIN main.dm_forecast_all_data_distributed fcst ON toStartOfFiveMinutes(dm.create_dttm) = toStartOfFiveMinutes(forecast_dttm)\r\n\tAND dm.owd_id = fcst.owd_id\r\n\tAND dm.lang = fcst.lang\r\n\tAND dm.city = fcst.city\r\nwhere owd_name = 'WeatherApi'\r\nand forecast_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\nand dm.lang = 'ru'\r\nand fcst.forecast_diff = 24\r\nGROUP BY dm.city\r\norder by `Точность прогноза`\r\nSETTINGS distributed_product_mode = 'allow'"
    }
   ]
  }
 ]
}