{
 "title": "Сравнение прогноза и фактической скорости ветра по городам",
 "description": "Скорость ветра по городам",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Скорость ветра (м/c) прогноза (последнего) и фактической  по источнику OpenWeatherMap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tfcst.forecast_dttm,\r\n\tdm.city as city,\r\n\tfcst.wind_speed as `Скорость пронгоз`,\r\n\tdm.wind_speed as `Скорость факт`\r\n  from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nJOIN main.dm_forecast_actual_data_distributed fcst ON toStartOfFiveMinutes(dm.create_dttm) = toStartOfFiveMinutes(forecast_dttm)\r\n\tAND dm.owd_id = fcst.owd_id\r\n\tAND dm.lang = fcst.lang\r\n\tAND dm.city = fcst.city\r\nwhere owd_name = 'OpenWeatherMap'\r\nand dm.lang = 'ru'\r\norder by dm.city\r\nSETTINGS distributed_product_mode = 'allow'"
    }
   ]
  },
  {
   "title": "Скорость ветра (м/c) прогноза (последнего) и фактической  по источнику WeatherApi",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tfcst.forecast_dttm,\r\n\tdm.city as city,\r\n\tfcst.wind_speed as `Скорость пронгоз`,\r\n\tdm.wind_speed as `Скорость факт`\r\n  from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nJOIN main.dm_forecast_actual_data_distributed fcst ON toStartOfFiveMinutes(dm.create_dttm) = toStartOfFiveMinutes(forecast_dttm)\r\n\tAND dm.owd_id = fcst.owd_id\r\n\tAND dm.lang = fcst.lang\r\n\tAND dm.city = fcst.city\r\nwhere owd_name = 'WeatherApi'\r\nand dm.lang = 'ru'\r\norder by dm.city\r\nSETTINGS distributed_product_mode = 'allow'"
    }
   ]
  },
  {
   "title": "Точность прогноза скорости ветра (%) по источнику OpenWeatherMap (по последнему прогнозу)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tfcst.forecast_dttm,\r\n\tdm.city as city,\r\n\t(1 + floor(IF(dm.wind_speed < fcst.wind_speed,(dm.wind_speed - fcst.wind_speed)/fcst.wind_speed, (fcst.wind_speed - dm.wind_speed)/dm.wind_speed), 2)) * 100 AS `Точность` from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nJOIN main.dm_forecast_actual_data_distributed fcst ON toStartOfFiveMinutes(dm.create_dttm) = toStartOfFiveMinutes(forecast_dttm)\r\n\tAND dm.owd_id = fcst.owd_id\r\n\tAND dm.lang = fcst.lang\r\n\tAND dm.city = fcst.city\r\nwhere owd_name = 'OpenWeatherMap'\r\nand dm.lang = 'ru'\r\norder by dm.city\r\nSETTINGS distributed_product_mode = 'allow'"
    }
   ]
  },
  {
   "title": "Точность прогноза скорости ветра (%) по источнику WeatherApi(по последнему прогнозу)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tfcst.forecast_dttm,\r\n\tdm.city as city,\r\n\t(1 + floor(IF(dm.wind_speed < fcst.wind_speed,(dm.wind_speed - fcst.wind_speed)/fcst.wind_speed, (fcst.wind_speed - dm.wind_speed)/dm.wind_speed), 2)) * 100 AS `Точность` from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nJOIN main.dm_forecast_actual_data_distributed fcst ON toStartOfFiveMinutes(dm.create_dttm) = toStartOfFiveMinutes(forecast_dttm)\r\n\tAND dm.owd_id = fcst.owd_id\r\n\tAND dm.lang = fcst.lang\r\n\tAND dm.city = fcst.city\r\nwhere owd_name = 'WeatherApi'\r\nand dm.lang = 'ru'\r\norder by dm.city\r\nSETTINGS distributed_product_mode = 'allow'"
    }
   ]
  },
  {
   "title": "Средняя точность прогноза скорости ветра (%) по источнику OpenWeatherMap (по последнему прогнозу)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tdm.city as city,\r\n\tfloor(avg((1 + floor(IF(dm.wind_speed < fcst.wind_speed,(dm.wind_speed - fcst.wind_speed)/fcst.wind_speed, (fcst.wind_speed - dm.wind_speed)/dm.wind_speed), 2)) * 100),2) AS `Точность прогноза`\r\nfrom main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nJOIN main.dm_forecast_actual_data_distributed fcst ON toStartOfFiveMinutes(dm.create_dttm) = toStartOfFiveMinutes(forecast_dttm)\r\n\tAND dm.owd_id = fcst.owd_id\r\n\tAND dm.lang = fcst.lang\r\n\tAND dm.city = fcst.city\r\nwhere owd_name = 'OpenWeatherMap'\r\nand dm.lang = 'ru'\r\nand forecast_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by dm.city\r\norder by `Точность прогноза`\r\nSETTINGS distributed_product_mode = 'allow'"
    }
   ]
  },
  {
   "title": "Средняя точность прогноза скорости ветра (%) по источнику WeatherApi(по последнему прогнозу)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tdm.city as city,\r\n\tfloor(avg((1 + floor(IF(dm.wind_speed < fcst.wind_speed,(dm.wind_speed - fcst.wind_speed)/fcst.wind_speed, (fcst.wind_speed - dm.wind_speed)/dm.wind_speed), 2)) * 100),2) AS `Точность прогноза`\r\nfrom main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nJOIN main.dm_forecast_actual_data_distributed fcst ON toStartOfFiveMinutes(dm.create_dttm) = toStartOfFiveMinutes(forecast_dttm)\r\n\tAND dm.owd_id = fcst.owd_id\r\n\tAND dm.lang = fcst.lang\r\n\tAND dm.city = fcst.city\r\nwhere owd_name = 'WeatherApi'\r\nand dm.lang = 'ru'\r\nand forecast_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by dm.city\r\norder by `Точность прогноза`\r\nSETTINGS distributed_product_mode = 'allow'"
    }
   ]
  },
  {
   "title": "Cкорость ветра (м/с) прогноза (по следующему дню) и фактической  по источнику OpenWeatherMap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tfcst.forecast_dttm,\r\n\tdm.city as city,\r\n\tfcst.wind_speed as `Скорость пронгоз`,\r\n\tdm.wind_speed as `Скорость факт`\r\n  from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nJOIN main.dm_forecast_all_data_distributed fcst ON toStartOfFiveMinutes(dm.create_dttm) = toStartOfFiveMinutes(forecast_dttm)\r\n\tAND dm.owd_id = fcst.owd_id\r\n\tAND dm.lang = fcst.lang\r\n\tAND dm.city = fcst.city\r\nwhere owd_name = 'OpenWeatherMap'\r\nand dm.lang = 'ru'\r\nand forecast_diff = 24\r\norder by dm.city\r\nSETTINGS distributed_product_mode = 'allow'"
    }
   ]
  },
  {
   "title": "Cкорость ветра (м/с) прогноза (по следующему дню) и фактической  по источнику WeatherApi",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tfcst.forecast_dttm,\r\n\tdm.city as city,\r\n\tfcst.wind_speed as `Скорость пронгоз`,\r\n\tdm.wind_speed as `Скорость факт`\r\n  from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nJOIN main.dm_forecast_all_data_distributed fcst ON toStartOfFiveMinutes(dm.create_dttm) = toStartOfFiveMinutes(forecast_dttm)\r\n\tAND dm.owd_id = fcst.owd_id\r\n\tAND dm.lang = fcst.lang\r\n\tAND dm.city = fcst.city\r\nwhere owd_name = 'WeatherApi'\r\nand dm.lang = 'ru'\r\nand forecast_diff = 24\r\norder by dm.city\r\nSETTINGS distributed_product_mode = 'allow'"
    }
   ]
  },
  {
   "title": "Точность прогноза скорости ветра (%) по источнику OpenWeatherMap (по следующему дню)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tfcst.forecast_dttm,\r\n\tdm.city as city,\r\n\t(1 + floor(IF(dm.wind_speed < fcst.wind_speed,(dm.wind_speed - fcst.wind_speed)/fcst.wind_speed, (fcst.wind_speed - dm.wind_speed)/dm.wind_speed), 2)) * 100 AS `Точность` from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nJOIN main.dm_forecast_all_data_distributed fcst ON toStartOfFiveMinutes(dm.create_dttm) = toStartOfFiveMinutes(forecast_dttm)\r\n\tAND dm.owd_id = fcst.owd_id\r\n\tAND dm.lang = fcst.lang\r\n\tAND dm.city = fcst.city\r\nwhere owd_name = 'OpenWeatherMap'\r\nand dm.lang = 'ru'\r\nand forecast_diff = 24\r\norder by dm.city\r\nSETTINGS distributed_product_mode = 'allow'"
    }
   ]
  },
  {
   "title": "Точность прогноза скорости ветра (%) по источнику WeatherApi (по следующему дню)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tfcst.forecast_dttm,\r\n\tdm.city as city,\r\n\t(1 + floor(IF(dm.wind_speed < fcst.wind_speed,(dm.wind_speed - fcst.wind_speed)/fcst.wind_speed, (fcst.wind_speed - dm.wind_speed)/dm.wind_speed), 2)) * 100 AS `Точность` from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nJOIN main.dm_forecast_all_data_distributed fcst ON toStartOfFiveMinutes(dm.create_dttm) = toStartOfFiveMinutes(forecast_dttm)\r\n\tAND dm.owd_id = fcst.owd_id\r\n\tAND dm.lang = fcst.lang\r\n\tAND dm.city = fcst.city\r\nwhere owd_name = 'WeatherApi'\r\nand dm.lang = 'ru'\r\nand forecast_diff = 24\r\norder by dm.city\r\nSETTINGS distributed_product_mode = 'allow'"
    }
   ]
  },
  {
   "title": "Средняя точность прогноза скорости ветра (%) по источнику OpenWeatherMap (по следующему дню)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tdm.city as city,\r\n\tfloor(avg((1 + floor(IF(dm.wind_speed < fcst.wind_speed,(dm.wind_speed - fcst.wind_speed)/fcst.wind_speed, (fcst.wind_speed - dm.wind_speed)/dm.wind_speed), 2)) * 100),2) AS `Точность прогноза` from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nJOIN main.dm_forecast_all_data_distributed fcst ON toStartOfFiveMinutes(dm.create_dttm) = toStartOfFiveMinutes(forecast_dttm)\r\n\tAND dm.owd_id = fcst.owd_id\r\n\tAND dm.lang = fcst.lang\r\n\tAND dm.city = fcst.city\r\nwhere owd_name = 'OpenWeatherMap'\r\nand dm.lang = 'ru'\r\nand forecast_diff = 24\r\nand forecast_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by dm.city\r\norder by `Точность прогноза`\r\nSETTINGS distributed_product_mode = 'allow'"
    }
   ]
  },
  {
   "title": "Средняя точность прогноза скорости ветра (%) по источнику WeatherApi (по следующему дню)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tdm.city as city,\r\n\tfloor(avg((1 + floor(IF(dm.wind_speed < fcst.wind_speed,(dm.wind_speed - fcst.wind_speed)/fcst.wind_speed, (fcst.wind_speed - dm.wind_speed)/dm.wind_speed), 2)) * 100),2) AS `Точность прогноза` from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nJOIN main.dm_forecast_all_data_distributed fcst ON toStartOfFiveMinutes(dm.create_dttm) = toStartOfFiveMinutes(forecast_dttm)\r\n\tAND dm.owd_id = fcst.owd_id\r\n\tAND dm.lang = fcst.lang\r\n\tAND dm.city = fcst.city\r\nwhere owd_name = 'WeatherApi'\r\nand dm.lang = 'ru'\r\nand forecast_diff = 24\r\nand forecast_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by dm.city\r\norder by `Точность прогноза`\r\nSETTINGS distributed_product_mode = 'allow'"
    }
   ]
  }
 ]
}