version: '3.7'
x-airflow-common:
  &airflow-common
  build: .
  image: ${AIRFLOW_IMAGE_NAME:-extending_airflow:latest}
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: 10
    AIRFLOW__WEBSERVER__SECRET_KEY: 'abc'
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/plugins:/opt/airflow/plugins
  user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-50000}"
  depends_on:
    postgres:
      condition: service_healthy
      
services:
  zookeeper:
    image: zookeeper:3.7
    container_name: zookeeper
    hostname: zookeeper
    networks:
      clickhouse-grafana-network:
        ipv4_address: 172.23.0.10
  clickhouse01:
    image: clickhouse/clickhouse-server:latest-alpine
    container_name: clickhouse01
    hostname: clickhouse01
    networks:
      clickhouse-grafana-network:
        ipv4_address: 172.23.0.11
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse/clickhouse01:/etc/clickhouse-server
    depends_on:
      - zookeeper
  clickhouse02:
    image: clickhouse/clickhouse-server:latest-alpine
    container_name: clickhouse02
    hostname: clickhouse02
    networks:
      clickhouse-grafana-network:
        ipv4_address: 172.23.0.12
    ports:
      - "8124:8123"
      - "9001:9000"
    volumes:
      - ./clickhouse/clickhouse02:/etc/clickhouse-server
    depends_on:
      - zookeeper
  clickhouse03:
    image: clickhouse/clickhouse-server:latest-alpine
    container_name: clickhouse03
    hostname: clickhouse03
    networks:
      clickhouse-grafana-network:
        ipv4_address: 172.23.0.13
    ports:
      - "8125:8123"
      - "9002:9000"
    volumes:
      - ./clickhouse/clickhouse03:/etc/clickhouse-server
    depends_on:
      - zookeeper
  clickhouse04:
    image: clickhouse/clickhouse-server:latest-alpine
    container_name: clickhouse04
    hostname: clickhouse04
    networks:
      clickhouse-grafana-network:
        ipv4_address: 172.23.0.14
    ports:
      - "8126:8123"
      - "9003:9000"
    volumes:
      - ./clickhouse/clickhouse04:/etc/clickhouse-server
    depends_on:
      - zookeeper
  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana-for-ch
    hostname: grafana
    networks:
      clickhouse-grafana-network:
        ipv4_address: 172.23.0.15
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/lib/plugins:/var/lib/grafana/plugins
      - ./grafana/lib/dashboards:/var/lib/grafana/dashboards
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - zookeeper

  postgres:
    image: postgres:13
    networks:
      clickhouse-grafana-network:
        ipv4_address: 172.23.0.16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    networks:
      clickhouse-grafana-network:
        ipv4_address: 172.23.0.17
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    networks:
      clickhouse-grafana-network:
        ipv4_address: 172.23.0.18
    restart: always

  airflow-init:
    <<: *airflow-common
    command: version
    networks:
      clickhouse-grafana-network:
        ipv4_address: 172.23.0.19
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}

volumes:
  postgres-db-volume:

networks:
  clickhouse-grafana-network:
    name: clickhouse-grafana-network
    ipam:
      config:
        - subnet: 172.23.0.0/24