{
 "title": "Атмосферное давление по городам",
 "description": "Атмосферное давление по городам",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Атмосферное давление (мм. рт. ст.) по источнику OpenWeatherMap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select create_dttm, city, atmospheric_pressure as `Давление` from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere owd_name = 'OpenWeatherMap'\r\nand lang = 'ru'\r\norder by city"
    }
   ]
  },
  {
   "title": "Атмосферное давление (мм. рт. ст.) по источнику WeatherApi",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select create_dttm, city, atmospheric_pressure as `Давление` from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere owd_name = 'WeatherApi'\r\nand lang = 'ru'\r\norder by city"
    }
   ]
  },
  {
   "title": "Среднее атмосферное давление (мм. рт. ст) по источнику OpenWeatherMap",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(avg(atmospheric_pressure),2) as value from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'ru'\r\nand owd_name = 'OpenWeatherMap'\r\nand create_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  },
  {
   "title": "Среднее атмосферное давление (мм. рт. ст.) по источнику WeatherApi",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(avg(atmospheric_pressure),2) as value from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'ru'\r\nand owd_name = 'WeatherApi'\r\nand create_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  },
  {
   "title": "Максимальное атмосферное давление (мм.рт.ст) по источнику OpenWeatherMap",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(max(atmospheric_pressure),2) as value from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'ru'\r\nand owd_name = 'OpenWeatherMap'\r\nand create_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  },
  {
   "title": "Максимальное атмосферное давление (мм. рт. ст.) по источнику WeatherApi",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(max(atmospheric_pressure),2) as value from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'ru'\r\nand owd_name = 'WeatherApi'\r\nand create_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  },
  {
   "title": "Минимальное атмосферное давление (мм. рт. ст.) по источнику OpenWeatherMap",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(min(atmospheric_pressure),2) as value from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'ru'\r\nand owd_name = 'OpenWeatherMap'\r\nand create_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  },
  {
   "title": "Минимальное атмосферное давление (мм. рт. ст.) по источнику WeatherApi",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(min(atmospheric_pressure),2) as value from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'ru'\r\nand owd_name = 'WeatherApi'\r\nand create_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  }
 ]
}