{
 "title": "Статистика по погодным данным",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Количество погодных данных по слоям (примерное)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT * from(\r\n  SELECT 'ODS Слой' AS `Слой`, sum(total_rows)*2 as `Количество данных` FROM system.tables\r\n  WHERE database = 'allsh'\r\n  UNION ALL\r\n  SELECT 'DS Слой' AS `Слой`, sum(total_rows) as `Количество данных` FROM system.tables\r\n  WHERE database = 'allrp'\r\n  AND name != 'ds_dim_owd'\r\n  AND name NOT LIKE '%buffer%'\r\n  UNION ALL\r\n  SELECT 'DM Слой' AS `Слой`, sum(total_rows)*2 as `Количество данных` FROM system.tables\r\n  WHERE database = 'main'\r\n  AND name NOT LIKE '%stg%'\r\n)\r\norder by `Количество данных`"
    }
   ]
  },
  {
   "title": "Размер погодных данных на диске (примерный)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT * from(\r\n  SELECT 'ODS Слой' AS `Слой`, sum(total_bytes)*2 as `Размер данных в байтах` FROM system.tables\r\n  WHERE database = 'allsh'\r\n  UNION ALL\r\n  SELECT 'DS Слой' AS `Слой`, sum(total_bytes) as `Размер данных в байтах` FROM system.tables\r\n  WHERE database = 'allrp'\r\n  AND name != 'ds_dim_owd'\r\n  AND name NOT LIKE '%buffer%'\r\n  UNION ALL\r\n  SELECT 'DM Слой' AS `Слой`, sum(total_bytes)*2 as `Размер данных в байтах` FROM system.tables\r\n  WHERE database = 'main'\r\n  AND name NOT LIKE '%stg%'\r\n)\r\norder by `Размер данных в байтах`"
    }
   ]
  },
  {
   "title": "Соотношение погодных данных от ОПД",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\n  'OpenWeatherMap' as `Оператор погодных данных`,\r\n  count() as `Количество погодных данных`\r\nfrom allsh.ods_raw_weather_data_distributed ods\r\njoin allrp.ds_dim_owd dim on dim.owd_id = ods.owd_id\r\nwhere owd_name = 'OpenWeatherMap'\r\nunion all\r\nselect \r\n  'WeatherApi' as `Оператор погодных данных`,\r\n  count() as `Количество погодных данных`\r\nfrom allsh.ods_raw_weather_data_distributed ods\r\njoin allrp.ds_dim_owd dim on dim.owd_id = ods.owd_id\r\nwhere owd_name = 'WeatherApi'"
    }
   ]
  }
 ]
}