{
 "title": "General weather condition by cities",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "General weather condition provided by OpenWeatherMap",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT general_condition as `Weather`, create_dttm, city from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere owd_name = 'OpenWeatherMap'\r\nand lang = 'en'\r\norder by city"
    }
   ]
  },
  {
   "title": "General weather condition provided by WeatherApi",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT general_condition as `Weather`, create_dttm, city from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere owd_name = 'WeatherApi'\r\nand lang = 'en'\r\norder by city"
    }
   ]
  },
  {
   "title": "Average weather condition provided by OpenWeatherMap",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT city as `City`, argMax(general_condition, num) from(\r\n  SELECT city, general_condition, COUNT(general_condition) AS num FROM main.dm_weather_data_distributed dm\r\n  join allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\n  WHERE lang = 'en'\r\n  AND owd_name = 'OpenWeatherMap'\r\n  and create_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\n  GROUP BY city, general_condition\r\n  ORDER BY city, num DESC)\r\nGROUP BY city"
    }
   ]
  },
  {
   "title": "Average weather condition provided by WeatherApi",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT city as `City`, argMax(general_condition, num) from(\r\n  SELECT city, general_condition, COUNT(general_condition) AS num FROM main.dm_weather_data_distributed dm\r\n  join allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\n  WHERE lang = 'en'\r\n  AND owd_name = 'WeatherApi'\r\n  and create_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\n  GROUP BY city, general_condition\r\n  ORDER BY city, num DESC)\r\nGROUP BY city"
    }
   ]
  },
  {
   "title": "cloudiness (%) provided by OpenWeatherMap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "select create_dttm, city, cloud_level as `Cloudiness` from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere owd_name = 'OpenWeatherMap'\r\nand lang = 'en'\r\norder by city"
    }
   ]
  },
  {
   "title": "cloudiness (%) provided by WeatherApi",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "rawSql": "select create_dttm, city, cloud_level as `Cloudiness` from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere owd_name = 'WeatherApi'\r\nand lang = 'en'\r\norder by city"
    }
   ]
  },
  {
   "title": "Average cloudiness (%) provided by OpenWeatherMap",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(avg(cloud_level),2) as value from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'en'\r\nand owd_name = 'OpenWeatherMap'\r\nand create_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  },
  {
   "title": "Average cloudiness (%) provided by WeatherApi",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(avg(cloud_level),2) as value from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'en'\r\nand owd_name = 'WeatherApi'\r\nand create_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  },
  {
   "title": "Maximum cloudiness (%) provided by OpenWeatherMap",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(max(cloud_level),2) as value from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'en'\r\nand owd_name = 'OpenWeatherMap'\r\nand create_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  },
  {
   "title": "Maximum cloudiness (%) provided by WeatherApi",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(max(cloud_level),2) as value from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'en'\r\nand owd_name = 'WeatherApi'\r\nand create_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  },
  {
   "title": "Minimum cloudiness (%) provided by OpenWeatherMap",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(min(cloud_level),2) as value from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'en'\r\nand owd_name = 'OpenWeatherMap'\r\nand create_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  },
  {
   "title": "Minimum cloudiness (%) provided by WeatherApi",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(min(cloud_level),2) as value from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'en'\r\nand owd_name = 'WeatherApi'\r\nand create_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  }
 ]
}