{
 "title": "Temperature by cities",
 "description": "Temperature by cities",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Temperature (°C) provided by OpenWeatherMap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select create_dttm, city, temp as `Temperature` from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere owd_name = 'OpenWeatherMap'\r\nand lang = 'en'\r\norder by city"
    }
   ]
  },
  {
   "title": "Temperature (°С) provided by WeatherApi",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select create_dttm, city, temp as `Temperature` from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere owd_name = 'WeatherApi'\r\nand lang = 'en'\r\norder by city"
    }
   ]
  },
  {
   "title": "Average temperature (°C) provided by OpenWeatherMap",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(avg(temp),2) as value from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'en'\r\nand create_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\nand owd_name = 'OpenWeatherMap'\r\ngroup by city\r\norder by value"
    }
   ]
  },
  {
   "title": "Average temperature (°C) provided by WeatherApi",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(avg(temp),2) as value from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'en'\r\nand owd_name = 'WeatherApi'\r\nand create_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  },
  {
   "title": "Maximum temperature (°C) provided by OpenWeatherMap",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(max(temp),2) as value from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'en'\r\nand owd_name = 'OpenWeatherMap'\r\nand create_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  },
  {
   "title": "Maximum temperature (°C) provided by WeatherApi",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(max(temp),2) as value from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'en'\r\nand owd_name = 'WeatherApi'\r\nand create_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  },
  {
   "title": "Minimum temperature (°C) provided by OpenWeatherMap",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(min(temp),2) as value from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'en'\r\nand owd_name = 'OpenWeatherMap'\r\nand create_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  },
  {
   "title": "Minimum temperature (°C) provided by WeatherApi",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(min(temp),2) as value from main.dm_weather_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'en'\r\nand owd_name = 'WeatherApi'\r\nand create_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  }
 ]
}