{
 "title": "Weather data statistics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Weather data count in layers (approximate)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT * from(\r\n  SELECT 'ODS Layer' AS `Layer`, sum(total_rows)*2 as `Data count` FROM system.tables\r\n  WHERE database = 'allsh'\r\n  UNION ALL\r\n  SELECT 'DS Layer' AS `Layer`, sum(total_rows) as `Data count` FROM system.tables\r\n  WHERE database = 'allrp'\r\n  AND name != 'ds_dim_owd'\r\n  AND name NOT LIKE '%buffer%'\r\n  UNION ALL\r\n  SELECT 'DM Layer' AS `Layer`, sum(total_rows)*2 as `Data count` FROM system.tables\r\n  WHERE database = 'main'\r\n  AND name NOT LIKE '%stg%'\r\n)\r\norder by `Data count`"
    }
   ]
  },
  {
   "title": "Weather data size on disk (approximate)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT * from(\r\n  SELECT 'ODS Layer' AS `Layer`, sum(total_bytes)*2 as `Weather data size in bytes` FROM system.tables\r\n  WHERE database = 'allsh'\r\n  UNION ALL\r\n  SELECT 'DS Layer' AS `Layer`, sum(total_bytes) as `Weather data size in bytes` FROM system.tables\r\n  WHERE database = 'allrp'\r\n  AND name != 'ds_dim_owd'\r\n  AND name NOT LIKE '%buffer%'\r\n  UNION ALL\r\n  SELECT 'DM Layer' AS `Layer`, sum(total_bytes)*2 as `Weather data size in bytes` FROM system.tables\r\n  WHERE database = 'main'\r\n  AND name NOT LIKE '%stg%'\r\n)\r\norder by `Weather data size in bytes`"
    }
   ]
  },
  {
   "title": "Correlation of OWD's weather data",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\n  'OpenWeatherMap' as `Weather Data Operator`,\r\n  count() as `Weather data count`\r\nfrom allsh.ods_raw_weather_data_distributed ods\r\njoin allrp.ds_dim_owd dim on dim.owd_id = ods.owd_id\r\nwhere owd_name = 'OpenWeatherMap'\r\nunion all\r\nselect \r\n  'WeatherApi' as `Weather Data Operator`,\r\n  count() as `Weather data count`\r\nfrom allsh.ods_raw_weather_data_distributed ods\r\njoin allrp.ds_dim_owd dim on dim.owd_id = ods.owd_id\r\nwhere owd_name = 'WeatherApi'"
    }
   ]
  }
 ]
}