{
 "title": "Погода (облачность и общее состояние) по городам (прогноз)",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Общее состояние погоды по источнику OpenWeatherMap",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT general_condition as `Погода`, forecast_dttm, city from main.dm_forecast_actual_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere owd_name = 'OpenWeatherMap'\r\nand lang = 'ru'\r\norder by city"
    }
   ]
  },
  {
   "title": "Общее состояние погоды по источнику WeatherApi",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT general_condition as `Погода`, forecast_dttm, city from main.dm_forecast_actual_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere owd_name = 'WeatherApi'\r\nand lang = 'ru'\r\norder by city"
    }
   ]
  },
  {
   "title": "Среднее состояние погоды по источнику OpenWeatherMap",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT city as `Город`, argMax(general_condition, num) AS `Направление ветра` from(\r\n  SELECT city, general_condition, COUNT(general_condition) AS num FROM main.dm_forecast_actual_data_distributed dm\r\n  join allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\n  WHERE lang = 'ru'\r\n  AND owd_name = 'OpenWeatherMap'\r\n  and forecast_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\n  GROUP BY city, general_condition\r\n  ORDER BY city, num DESC)\r\nGROUP BY city"
    }
   ]
  },
  {
   "title": "Среднее состояние погоды по источнику WeatherApi",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT city as `Город`, argMax(general_condition, num) AS `Направление ветра` from(\r\n  SELECT city, general_condition, COUNT(general_condition) AS num FROM main.dm_forecast_actual_data_distributed dm\r\n  join allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\n  WHERE lang = 'ru'\r\n  AND owd_name = 'WeatherApi'\r\n  and forecast_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\n  GROUP BY city, general_condition\r\n  ORDER BY city, num DESC)\r\nGROUP BY city"
    }
   ]
  },
  {
   "title": "Облачность (%) по источнику OpenWeatherMap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "select forecast_dttm, city, cloud_level as `Облачность` from main.dm_forecast_actual_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere owd_name = 'OpenWeatherMap'\r\nand lang = 'ru'\r\norder by city"
    }
   ]
  },
  {
   "title": "Облачность (%) по источнику WeatherApi",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "rawSql": "select forecast_dttm, city, cloud_level as `Облачность` from main.dm_forecast_actual_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere owd_name = 'WeatherApi'\r\nand lang = 'ru'\r\norder by city"
    }
   ]
  },
  {
   "title": "Средняя облачность (%) по источнику OpenWeatherMap",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(avg(cloud_level),2) as value from main.dm_forecast_actual_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'ru'\r\nand owd_name = 'OpenWeatherMap'\r\nand forecast_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  },
  {
   "title": "Средняя облачность (%) по источнику WeatherApi",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(avg(cloud_level),2) as value from main.dm_forecast_actual_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'ru'\r\nand owd_name = 'WeatherApi'\r\nand forecast_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  },
  {
   "title": "Максимальная облачность (%) по источнику OpenWeatherMap",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(max(cloud_level),2) as value from main.dm_forecast_actual_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'ru'\r\nand owd_name = 'OpenWeatherMap'\r\nand forecast_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  },
  {
   "title": "Максимальная облачность (%) по источнику WeatherApi",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(max(cloud_level),2) as value from main.dm_forecast_actual_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'ru'\r\nand owd_name = 'WeatherApi'\r\nand forecast_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  },
  {
   "title": "Минимальная облачность (%) по источнику OpenWeatherMap",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(min(cloud_level),2) as value from main.dm_forecast_actual_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'ru'\r\nand owd_name = 'OpenWeatherMap'\r\nand forecast_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  },
  {
   "title": "Минимальная облачность (%) по источнику WeatherApi",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(min(cloud_level),2) as value from main.dm_forecast_actual_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'ru'\r\nand owd_name = 'WeatherApi'\r\nand forecast_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  }
 ]
}