{
 "title": "Температура по городам (прогноз)",
 "description": "Температура по городам",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Температура (°C) по источнику OpenWeatherMap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select forecast_dttm, city, temp as `Температура` from main.dm_forecast_actual_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere owd_name = 'OpenWeatherMap'\r\nand lang = 'ru'\r\norder by city"
    }
   ]
  },
  {
   "title": "Температура (°С) по источнику WeatherApi",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select forecast_dttm, city, temp as `Температура` from main.dm_forecast_actual_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere owd_name = 'WeatherApi'\r\nand lang = 'ru'\r\norder by city"
    }
   ]
  },
  {
   "title": "Средняя температура (°C) по источнику OpenWeatherMap",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(avg(temp),2) as value from main.dm_forecast_actual_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'ru'\r\nand forecast_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\nand owd_name = 'OpenWeatherMap'\r\ngroup by city\r\norder by value"
    }
   ]
  },
  {
   "title": "Средняя температура (°C) по источнику WeatherApi",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(avg(temp),2) as value from main.dm_forecast_actual_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'ru'\r\nand owd_name = 'WeatherApi'\r\nand forecast_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  },
  {
   "title": "Максимальная температура (°C) по источнику OpenWeatherMap",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(max(temp),2) as value from main.dm_forecast_actual_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'ru'\r\nand owd_name = 'OpenWeatherMap'\r\nand forecast_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  },
  {
   "title": "Максимальная температура (°C) по источнику WeatherApi",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(max(temp),2) as value from main.dm_forecast_actual_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'ru'\r\nand owd_name = 'WeatherApi'\r\nand forecast_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  },
  {
   "title": "Минимальная температура (°C) по источнику OpenWeatherMap",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(min(temp),2) as value from main.dm_forecast_actual_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'ru'\r\nand owd_name = 'OpenWeatherMap'\r\nand forecast_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  },
  {
   "title": "Минимальная температура (°C) по источнику WeatherApi",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(min(temp),2) as value from main.dm_forecast_actual_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'ru'\r\nand owd_name = 'WeatherApi'\r\nand forecast_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  }
 ]
}