{
 "title": "Ветер по городам (прогноз)",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Скорость ветра (м/с) по источнику OpenWeatherMap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select forecast_dttm, city, wind_speed as `Скорость ветра` from main.dm_forecast_actual_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere owd_name = 'OpenWeatherMap'\r\nand lang = 'ru'\r\norder by city"
    }
   ]
  },
  {
   "title": "Скорость ветра (м/с) по источнику WeatherApi",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select forecast_dttm, city, wind_speed as `Скорость ветра` from main.dm_forecast_actual_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere owd_name = 'WeatherApi'\r\nand lang = 'ru'\r\norder by city"
    }
   ]
  },
  {
   "title": "Средняя скорость ветра (м/с) по источнику OpenWeatherMap",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(avg(wind_speed),2) as value from main.dm_forecast_actual_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'ru'\r\nand owd_name = 'OpenWeatherMap'\r\nand forecast_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  },
  {
   "title": "Средняя скорость ветра (м/с) по источнику WeatherApi",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(avg(wind_speed),2) as value from main.dm_forecast_actual_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'ru'\r\nand owd_name = 'WeatherApi'\r\nand forecast_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  },
  {
   "title": "Максимальная скорость ветра (м/с) по источнику OpenWeatherMap",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(max(wind_speed),2) as value from main.dm_forecast_actual_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'ru'\r\nand owd_name = 'OpenWeatherMap'\r\nand forecast_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  },
  {
   "title": "Максимальная скорость ветра (м/с) по источнику WeatherApi",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(max(wind_speed),2) as value from main.dm_forecast_actual_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'ru'\r\nand owd_name = 'WeatherApi'\r\nand forecast_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  },
  {
   "title": "Минимальная скорость ветра (м/с) по источнику OpenWeatherMap",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(min(wind_speed),2) as value from main.dm_forecast_actual_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'ru'\r\nand owd_name = 'OpenWeatherMap'\r\nand forecast_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  },
  {
   "title": "Минимальная скорость ветра (м/с) по источнику WeatherApi",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT city, floor(min(wind_speed),2) as value from main.dm_forecast_actual_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere lang = 'ru'\r\nand owd_name = 'WeatherApi'\r\nand forecast_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\ngroup by city\r\norder by value"
    }
   ]
  },
  {
   "title": "Направление ветра по источнику OpenWeatherMap",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT wind_direction as `Направление ветра`, forecast_dttm, city from main.dm_forecast_actual_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere owd_name = 'OpenWeatherMap'\r\nand lang = 'ru'\r\norder by city"
    }
   ]
  },
  {
   "title": "Направление ветра по источнику WeatherApi",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT wind_direction as `Направление ветра`, forecast_dttm, city from main.dm_forecast_actual_data_distributed dm\r\njoin allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\nwhere owd_name = 'WeatherApi'\r\nand lang = 'ru'\r\norder by city"
    }
   ]
  },
  {
   "title": "Среднее направление ветра по источнику OpenWeatherMap",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT city as `Город`, argMax(wind_direction, num) AS `Направление ветра` from(\r\n  SELECT city, wind_direction, COUNT(wind_direction) AS num FROM main.dm_forecast_actual_data_distributed dm\r\n  join allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\n  WHERE lang = 'ru'\r\n  AND owd_name = 'OpenWeatherMap'\r\n  and forecast_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\n  GROUP BY city, wind_direction\r\n  ORDER BY city, num DESC)\r\nGROUP BY city"
    }
   ]
  },
  {
   "title": "Среднее направление ветра по источнику WeatherApi",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT city as `Город`, argMax(wind_direction, num) AS `Направление ветра` from(\r\n  SELECT city, wind_direction, COUNT(wind_direction) AS num FROM main.dm_forecast_actual_data_distributed dm\r\n  join allrp.ds_dim_owd dim on dm.owd_id = dim.owd_id\r\n  WHERE lang = 'ru'\r\n  AND owd_name = 'WeatherApi'\r\n  and forecast_dttm BETWEEN parseDateTime64BestEffortOrZero('${__from:date}') AND parseDateTime64BestEffortOrZero('${__to:date}')\r\n  GROUP BY city, wind_direction\r\n  ORDER BY city, num DESC)\r\nGROUP BY city"
    }
   ]
  }
 ]
}